name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub (Optional)
      if: ${{ secrets.DOCKER_USERNAME != '' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t html5up-site .

    # Optional: push image to Docker Hub
    - name: Push to Docker Hub
      if: ${{ secrets.DOCKER_USERNAME != '' }}
      run: |
        docker tag html5up-site ${{ secrets.DOCKER_USERNAME }}/html5up-site:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/html5up-site:latest
